server:
    port: 11001
logging:
    level:
        org.springframework.web: trace
        org.springframework.security: trace
spring:
    cloud:
        gateway:
            routes:
                - id: auth-server
                  uri: http://127.0.0.1:9090/
                  predicates:
                      - Path=/auth/**
                      - StripPrefix=1

